### ISSUE TITLE
Add a `plot()` method to the Queueing Network

### ISSUE THREAD

**Issue by drvinceknight** [CiwPython/Ciw#1]
This would tap in to the networkx code and produce a graphics object:

So something like:

    >>> Q = asq.Simulation(params_dict)
    >>> p = Q.plot()  # This would return a networkx/matplotlib plot
    >>> p.show() 
    >>> p.save() # etc...

Just a nice quick way to get a visualisation of the network? As it's already networkx underneath this would be easy enough to implement (I'd like to take this one). What do you think?

**Comment by drvinceknight** [comment]
Looking at:

```
   15 class Simulation:
   16     """
   17     Overall simulation class
   18     """
   19     def __init__(self, *args, **kwargs):
   20         """
   21         Initialise a queue instance.
   22         """
   23         if args:
   24             parameters = args[0]
   25         else:
   26             parameters = kwargs
   27         self.parameters = parameters
   28         self.number_of_nodes = self.parameters['Number_of_nodes']
   29         self.detecting_deadlock = self.parameters['detect_deadlock']
   30         self.digraph = nx.DiGraph()
```

Is the `digraph` constructed at any point? It seems to be used in the detect deadlock but not immediate where the graph gets constructed. Can you point that out?

**Comment by geraintpalmer** [comment]
The DiGraph has no nodes at this point. Nodes get added when Servers are created (in the __init__ of the Node, which are created in this __init__  further down). So by the end of this __init__ method the DiGraph will have nodes.

**Comment by drvinceknight** [comment]
> So by the end of this init method the DiGraph will have nodes.

By the end of the `__init__` for the Simulation right?

Didn't seem to get that behaviour, will investigate more. Thanks!

**Comment by geraintpalmer** [comment]
The Node's _ _ init _ _ has this code:

        if self.c < 'Inf':
            self.servers = [Server(self, i+1) for i in range(self.c)]
            if simulation.detecting_deadlock:
                self.simulation.digraph.add_nodes_from([str(s) for s in self.servers])


So detect_deadlock needs to be True, and cannot have Infinite servers.

**Comment by drvinceknight** [comment]
Right so the `DiGraph` object is only created if the `detect_deadlock`
method is created?

Cool. For the purposes of the plot, I will create a new graph object I
think, what do you reckon?

**Comment by geraintpalmer** [comment]
Yeah. Digraph needs a finite amount of servers, so doesn't work with infinite servers. Also to save time we only build up the digraph if we need it, so if no deadlock no point.

Best create a new digraph of your own, that can cope with infinite servers (no need to have each server as a node right?)

**Comment by drvinceknight** [comment]
> (no need to have each server as a node right?)

Yeah, great point. Will roll with that...

**Comment by geraintpalmer** [comment]
Whereas that's the point of the state digraph, no other info really.

**Comment by drvinceknight** [comment]
Yeah... My initial idea to just build on the graph that's there already was
nonsense... No bother, recreating a new graph is not that much work. Will
maybe get to this tomorrow: I'm all over hypothesis at the moment.

**Comment by drvinceknight** [comment]
After our chat, I'm closing this. Re open if you'd like to.
