### ISSUE TITLE
Allow 'TimeDependent' functions for Batching_distributions

### ISSUE THREAD

**Issue by caipirginka** [CiwPython/Ciw#135]
Was there a specific reason not to accept them?

I already tried with a quick-and-dirty change to the existing code to accept them and apparently it works.

I have a use case where i must simulate a take-away pizzeria.
When a new ordering comes in, I must check if it's acceptable or not.
Each ordering has a quantity of pizzas and the requested time of pickup.
Let's say the oven can accomodate 4 pizzas at a time, so I have 4 servers.
A pizza takes 5 minutes to cook, so it must enter the system exactly 5 minutes before the requested pickup time.
In this case i do not have a probabilistic distribution of arrivals, because I know exactly when each pizza must enter the oven.
But each ordering may request more than one pizza so, in addition to a 'TimeDependent' function for next time of arrival, I need a 'TimeDependent' function for number of individuals entering the system each time.
I could then run a simulation using the already accepted orderings AND the new one and see if it gets out of the system in time for pickup.
If it does not, I'll refuse it.
I'm new to queue theory, so I'm not sure if this is the best way to model such a use case.
If it is, then 'TimeDependent' functions should be allowed for Batching_distributions.

Thanks a lot!!!

**Comment by geraintpalmer** [comment]
Hi @caipirginka this is a great idea. I think this will be a nice new feature for the library. When I get time next week I'll try to implement this and draft a new release. Thanks for your interest!
