### ISSUE TITLE
Ensure consistant number of nodes is used throughout

### ISSUE THREAD

**Issue by achercasky** [CiwPython/Ciw#137]
Hi everyone, I´m getting this error " Ensure consistant number of nodes is used throughout"

This happens when i try to use two service distributions.

```
N = ciw.create_network(
    Arrival_distributions=[['Exponential', media]],
    Service_distributions=[['Uniform', 2, 15], ['Normal', 50, 20]],
    Number_of_servers=[1,1])
```

**Comment by geraintpalmer** [comment]
HI @achercasky, How many nodes are in your network?

From the `Arrival_distributions` it looks like you have 1 node (a list of length 1, with 1 distribution)
But from `Service_distributions` and `Number_of_servers` it looks like you want 2 nodes.

If both Nodes need the same arrival distribution, then you would have to repeat it, e.g.

```
    Arrival_distributions=[['Exponential', media], ['Exponential', media]],
```

When using more than 1 node, you also need a transition matrix: http://ciw.readthedocs.io/en/latest/Tutorial-II/tutorial_v.html

Does that help at all?

**Comment by achercasky** [comment]
If i use 1 server, I will get the same error. The Service_distributions is the same as the example "Customers wanting both hot and cold food must first queue for cold food, then hot food, and then take both to the till and pay."

**Comment by geraintpalmer** [comment]
OK, if I understand correctly, you have 2 service centres:
+ the first with service distribution `['Uniform', 2, 15]`
+ the second with service distribution `['Normal', 50, 20]` (Note that Ciw does not support a Normal distribution, only a [Truncated Normal distribution](http://ciw.readthedocs.io/en/latest/Reference/distributions.html#normal-dist))

Customers arrive to the first node, are served, but them must join the second node, get served, before leaving.

Is this correct?

**Comment by achercasky** [comment]
That´s correct. They must go throw both service distributions. So the total amount spent will be between both on them.

**Comment by geraintpalmer** [comment]
Hi @achercasky sorry for the delay:

I believe you want one of two things:

+ either two Nodes in series (customers queue for the fist node with service distribution `['Uniform', 2, 15]`, then join *another* queue with service distribution `['Normal', 50, 20]`

for this, each node needs an arrival distribution (though the second node will have `NoArrivals`). And also a transition matrix, e.g.:

```
N = ciw.create_network(
    Arrival_distributions=[['Exponential', media], 'NoArrivals'],
    Service_distributions=[['Uniform', 2, 15], ['Normal', 50, 20]],
    Number_of_servers=[1,1],
    Transition_matrices=[[0.0, 1.0], [0.0, 0.0]]
)
```

+ or you have one Node, where the service time consists of two times, the first part sampled from `[['Uniform', 2, 15]`, and the second from  `['Normal', 50, 20]`. For this you will have to create your own distribution and use the `UserDefined` distribution option, e.g.

```
def doubledistribution():
    part1 = random.uniform(2, 15)
    part2 = random.normalvariate(50, 20)
    return part1 + part 2

N = ciw.create_network(
    Arrival_distributions=[['Exponential', media]],
    Service_distributions=[['UserDefined', doubledistribution]],
    Number_of_servers=[1]
)
```

These two options model two very different things, and will produce very different outcomes.

**_Note:_** If using the 1st option Ciw does not support `Normal` distribution, use [`TruncatedNormal`](http://ciw.readthedocs.io/en/latest/Reference/distributions.html#normal-dist) instead. If using 2nd option, ensure that `doubledistribution` does not sample negative numbers (a danger when using a Normal distribution).

**Comment by geraintpalmer** [comment]
Closing this for now, if anything else is needed please reopen!
