### ISSUE TITLE
when I run your exmaple coe MM1 in pycharm, I found error

### ISSUE THREAD

**Issue by khunetworking** [CiwPython/Ciw#139]
when I run your exmaple coe MM1 in pycharm, I found error

 N = ciw.create_network(params)
  File "C:\Users\Dkay\Anaconda3\envs\tensorflow\lib\site-packages\ciw-1.1.3-py3.5.egg\ciw\import_params.py", line 20, in create_network
ValueError: Arrival_distributions, Service_distributions and Number_of_servers are required arguments.

and this is whole code. 
import ciw
import ciw.import_params
import matplotlib.pyplot as plt

params = {
    'Arrival_distributions': [['Exponential', 3.0]],
    'Service_distributions': [['Exponential', 5.0]],
    'Transition_matrices': [[0.0]],
    'Number_of_servers': [1]
}

N = ciw.create_network(params)
Q = ciw.Simulation(N)

traffic_intensity = params['Arrival_distributions'][0][1] / params['Service_distributions'][0][1]
expected_queue_length = traffic_intensity / (1 - traffic_intensity)
print(expected_queue_length)
expected_waiting_time = expected_queue_length / params['Service_distributions'][0][1]
print(expected_waiting_time)

recs = Q.get_all_records()

waits = [r.waiting_time for r in recs if r.arrival_date > 50]
simulation_mean_wait = sum(waits)/len(waits)
print(simulation_mean_wait)
def mean_queue_length(recs, max_sim_time, warm_up):
    arrival_time_stamps = [(r.arrival_date, r.queue_size_at_arrival) for r in recs]
    exit_time_stamps = [(r.exit_date, r.queue_size_at_departure) for r in recs]
    time_stamps = arrival_time_stamps + exit_time_stamps + [(0, 0)]
    time_stamps.sort(key=lambda r: r[0])
    numerator = sum([time_stamps[i][1]*(time_stamps[i][0]-time_stamps[i-1][0]) for i in range(1, len(time_stamps)) if time_stamps[i][0] > 50])
    mean_queue_length = numerator / (max_sim_time - warm_up)
    return mean_queue_length

simulation_mean_queue_length = mean_queue_length(recs, max_sim_time, 50)
print(simulation_mean_queue_length)

print("Analytical mean waiting time: " + str(expected_waiting_time))
print("Simulation mean waiting time: " + str(simulation_mean_wait))
print("Analytical mean queue length: " + str(expected_queue_length))
print("Simulation mean queue length: " + str(simulation_mean_queue_length))

**Comment by khunetworking** [comment]
and I already run in jupyter and there was same error

**Comment by drvinceknight** [comment]
> N = ciw.create_network(params)

This line should be:

```
N = ciw.create_network(**params)
```

(Note the `**`)


Or you can directly pass the arguments to `create_network` without creating `params`:

```
N = ciw.create_network(Arrival_distributions=[['Exponential', 3.0]],
                       Service_distributions=[['Exponential', 5.0]],
                       Transition_matrices=[[0.0]],
                       Number_of_servers=[1])
```

Perhaps you are looking at some older documentation, where the approach you are using was correct (for an older version of `Ciw`). Current documentation is available here: http://ciw.readthedocs.io/en/latest/Tutorial-I/tutorial_i.html

**Comment by khunetworking** [comment]
Thanks for your attention of my Question.
It works ! 
Thanks again sincerely :)

**Comment by geraintpalmer** [comment]
Great! closing this but feel free to ask further questions on Gitter if that doesn't answer everything :D
