### ISSUE TITLE
I want to know node

### ISSUE THREAD

**Issue by khunetworking** [CiwPython/Ciw#140]
first of all, I appreciate your codes because I have learn many things...

but I confuse about the difference server and node .... node contains several servers ? or server contains several nodes ?
and one more question!

When I set Number of server like 3, can I calculate utilisation of each server?

when I see http://ciw.readthedocs.io/en/latest/Tutorial-I/tutorial_iii.html
I can't understand about transitive_nodes[0].... 

please help me to understand

**Comment by khunetworking** [comment]
And addtional question... for example Number of server like 3 ,Can I express the utilization of each server in a graph over time? The Questions are very important issues for me... please help me

**Comment by khunetworking** [comment]
Can I create network system like just one cutomer node and 3node so individual select specific node ?

**Comment by geraintpalmer** [comment]
HI @khunetworking 

IF you run the code in that tutorial, you'll see:

```
>>> Q.transitive_nodes[0]
[Node 1]
```

Here `transitive_nodes` are all the service centers that you simulate.

Each node has a number of servers:

```
Q.transitive_nodes[0].servers
[Server 1 at Node 1, Server 2 at Node 1, Server 3 at Node 1]
```

And each of the servers has their own utilisation:

```
Q.transitive_nodes[0].servers[0].utilisation
0.7219984577464381
```

The utilisation of the node is the utilisation of all the servers (and in general is a more useful measure of workforce utilisation).

I hope that helps!

**Comment by geraintpalmer** [comment]
> Can I create network system like just one cutomer node and 3node so individual select specific node ?

I do not understand what you mean here. Can you clarify?

**Comment by geraintpalmer** [comment]
Closing this for now, If more is required please reopen.
