### ISSUE TITLE
Install for Python 3 ?

### ISSUE THREAD

**Issue by GH89** [CiwPython/Ciw#142]
import ciw runs perfectly fine and imports the module while using python 2. But if I run it using using python 3, it gives a module not found error. I ran pip install ciw from the terminal and  I am using a mac.

**Comment by drvinceknight** [comment]
Hi @GH89 ciw is regularly tested on various python versions so I suspect you are not actually installing in to your python 3 environment. Could you try:

```
$ pip3 install ciw
```

If that doesn't fix your issue, can you type (in your terminal, the following 4 different commands):

```
$ which python
```

```
$ which pip
```

```
$ which python3
```

```
$ which pip3
```

and for each of those separate commands let me know what the terminal outputs back?

**Comment by GH89** [comment]
Thanks a lot @drvinceknight , it works now. I had initially tried pip3 install but it had not worked due to some permission errors. Strangely, it ran perfectly this time and I am able to import ciw.

**Comment by drvinceknight** [comment]
Great! FYI, python 2 and python 3 are essentially two different software environments on your computer so when you install something for one of them, that doesn't mean it's there for the other one.

Enjoy using ciw :+1: :)

**Comment by geraintpalmer** [comment]
Closing this, thanks @drvinceknight for helping!
