### ISSUE TITLE
Investigate use of `collections.deque` as containers for individuals in nodes

### ISSUE THREAD

**Issue by drvinceknight** [CiwPython/Ciw#144]
Currently lists are used but `deques` ("list-like container with fast appends and pops on either end") :https://docs.python.org/2/library/collections.html#collections.deque offer significant speed improvements for actions like `append` and `pop`.

This is due to the fact that lists have to copy and reindex each element during a `pop`.

I believe the only methods needed would be: `append` and `popleft` (we need to specify which type of `pop`) we want.

`deque`s are in the standard lib (in `collections`) and are in py2.4+

Example of the functionality that I believe we need:

```
>>> import collections
>>> queue = collections.deque()
>>> queue
deque([])
>>> for ind in [1, 4, 5]:
...    queue.append(ind)
>>> queue
deque([1, 4, 5])
>>> len(queue)
3
>>> queue.popleft()
1
>>> queue.popleft()
4
>>> len(queue), queue
1, deque([5])
```

We should see what this would do performance wise by using the timing benchmarks used in the paper.

**Comment by drvinceknight** [comment]
This episode of Talk Python to Me has a nice discussion about this (and many other things): https://talkpython.fm/episodes/show/141/python-tricks

**Comment by geraintpalmer** [comment]
deque does not allow popping from the middle of a list. Ciw needs this.

**Comment by drvinceknight** [comment]
> deque does not allow popping from the middle of a list. Ciw needs this.

Surmountable:

```python
>>> def pop(deque, index=0):
...     deque.rotate(-index)
...     element = deque.popleft()
...     deque.rotate(index)
...     return element
>>> import collections
>>> queue = collections.deque(range(10))
>>> queue
deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> pop(deque=queue)
0
>>> queue
deque([1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> pop(deque=queue, index=3)
4
>>> queue
deque([1, 2, 3, 5, 6, 7, 8, 9])
```

**Note*** there's a slight issue when using negative `index` (when rotating back the other way) but that would be surmountable if needed.

```python
>>> pop(deque=queue, index=-2)
8
>>> queue  way)
deque([2, 3, 5, 6, 7, 9, 1])
```

In py3.5+ deque also has an `index` method (but if you want to stick with py2 for longer we can figure that out if you need `index` too).

If we made this change (which we should investigate, there might or might not be a big performance improvement) there will no doubt be a few things where we need to think of things differently than when using lists.
