### ISSUE TITLE
ValueError appears in tutorial, following use of dictionary in ciw.create_network()

### ISSUE THREAD

**Issue by markz1er** [CiwPython/Ciw#148]
Hi all, I have tried in two virtualenvs with both python 2.7 and 3.6 to follow the tutorial found here https://github.com/CiwPython/Ciw-notebooks/blob/master/Basic%20Queueing%20Network.ipynb

However in both cases the following error appears:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-f4bf8c20e291> in <module>()
      8     'Transition_matrices': {'Class 0': [[0.0, 0.2], [0.1, 0.0]]}
      9 }
---> 10 N = ciw.create_network(data)
     11 Q = ciw.Simulation(N)

/anaconda3/lib/python3.6/site-packages/ciw/import_params.py in create_network(Arrival_distributions, Baulking_functions, Class_change_matrices, Number_of_servers, Priority_classes, Queue_capacities, Service_distributions, Transition_matrices, Batching_distributions)
     18     """
     19     if Arrival_distributions == None or Number_of_servers == None or Service_distributions == None:
---> 20         raise ValueError('Arrival_distributions, Service_distributions and Number_of_servers are required arguments.')
     21 
     22     params = {

ValueError: Arrival_distributions, Service_distributions and Number_of_servers are required arguments.

Please could someone have a look at this? Thanks

**Comment by geraintpalmer** [comment]
Hi @markz1er, this error is due to the notebooks being out of date with the latest version of Ciw. They will be updated today, thanks for finding this!

**Comment by geraintpalmer** [comment]
They are updated now.
