### ISSUE TITLE
Make work with latest versions of Networkx and Pyyaml

### ISSUE THREAD

**Issue by geraintpalmer** [CiwPython/Ciw#155]

**Comment by drvinceknight** [comment]
Just ran in to this when pip installing (and then pip fell over because of something about pyyaml): would also be good to unpin (and just lower bound) the requirements.

**Comment by geraintpalmer** [comment]
Sorted in commit 0daf6a28259bcb7e601f01910a947faea35a4aa5, will be part of next release.

**Comment by geraintpalmer** [comment]
Implemented with commit 0daf6a28259bcb7e601f01
