### ISSUE TITLE
Limit the NodePopulation Tracker to a subset of nodes

### ISSUE THREAD

**Issue by guglielmosanchini** [CiwPython/Ciw#172]
It would be useful to be able to limit the tracking of customers at every node to just a subset of nodes, to increase speed and effectiveness. 
In a system I am working on, with approximately 600 nodes, I would just like to track a few of those. In my current settings, adding the tracker increases the execution time from 60 seconds to 90 seconds

**Comment by geraintpalmer** [comment]
Hi @guglielmosanchini thanks for the issue!

I'll be pushing up a small fix to the state trackers today which should improve speed. This will also enable you to do what you're asking for. I'll send a follow up message later.

**Comment by geraintpalmer** [comment]
@guglielmosanchini 

Please take a look at the latest release (v2.1.1) released just now.

It has a new state tracker that can limit the number of nodes it observes: https://ciw.readthedocs.io/en/latest/Reference/state_trackers.html#nodepopsubset

In addition the state tracker is now slightly more efficient, only recording a state change if the state really does change (an not for example changing from one state to the same state).

Hope this improves things for you.

**Comment by guglielmosanchini** [comment]
Thank you, it is much faster now!
Consider that the fact it is uses indexes and not the node numbers themselves could be deceiving, and that it doesnt throw an error if you input a number greater than the total_num_of_nodes.
Thank you very very much
