### ISSUE TITLE
Is there any limitation for network size in ciw?

### ISSUE THREAD

**Issue by neetu5510** [CiwPython/Ciw#176]
I am trying to simulate a network using ciw but it always gives the error 'module' object is not callable'. Can you explain why? I am taking 2 class of customers and trying to simulate a 13 node network. Is there some limitation on number of nodes for the network?

**Comment by geraintpalmer** [comment]
Thanks @neetu5510 
There is no limit on Network size, as long as it all fits in memory.

The error 'module' object is not callable' looks like a syntax error to me. Can you post the code?

**Comment by neetu5510** [comment]
`N=ciw.create_network(
  arrival_distributions= {'Class 0':[ciw.dists.Exponential(.1),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals()],
                          'Class 1':[ciw.dists.Exponential(.15),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals()]},
 service_distributions={'Class 0':[ciw.dists.Exponential(.5),
                                   ciw.dists.Exponential(.03),
                                   ciw.dists.Exponential(.025),
                                   ciw.dists.Exponential(.02),
                                   ciw.dists.Exponential(.021),
                                   ciw.dists.Exponential(.02),
                                   ciw.dists.Exponential(.019),
                                   ciw.dists.Exponential(.018),
                                   ciw.dists.Exponential(.015),
                                   ciw.dists.Exponential(.014),
                                   ciw.dists.Exponential(.012),
                                   ciw.dists.Exponential(.01),
                                   ciw.dists.Exponential(.09)],
                         'Class 1':[ciw.dists.Exponential(.06),
                                    ciw.dists.Exponential(.05),
                                    ciw.dists.Exponential(.045),
                                    ciw.dists.Exponential(.04),
                                    ciw.dists.Exponential(.035),
                                    ciw.dists.Exponential(.03),
                                    ciw.dists.Exponential(.025),
                                    ciw.dists.Exponential(.024),
                                    ciw.dists.Exponential(.023),
                                    ciw.dists.Exponential(.022),
                                    ciw.dists.Exponential(.02),
                                    ciw.dists.Exponential(.018),
                                    ciw.dists.Exponential(.015)]},
 routing= {'Class 0':[[0,1,0,0,0,0,0,0,0,0,0,0,0],
                      [0,0,0.1,0.2,0.1,0.02,0.04,0.08,0.05,0.03,0.08,0.1,0],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,0]],
           'Class 1':[[0,1,0,0,0,0,0,0,0,0,0,0,0],
                      [0,0,0.1,0.3,0.1,0.02,0.04,0.08,0.05,0.03,0.08,0.1,0],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,0]],
          },
 number_of_servers=[3,2,1,1,1,1,1,1,1,1,1,1,2]
)
ciw.seed(2)
Q=ciw.simulation(N)
Q.simulate_until_max_time(1440)`

**Comment by neetu5510** [comment]
I am trying this code:
`import ciw
import numpy as np
N=ciw.create_network(
  arrival_distributions= {'Class 0':[ciw.dists.Exponential(.1),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals()],
                          'Class 1':[ciw.dists.Exponential(.15),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals(),
                                     ciw.dists.NoArrivals()]},
 service_distributions={'Class 0':[ciw.dists.Exponential(.5),
                                   ciw.dists.Exponential(.03),
                                   ciw.dists.Exponential(.025),
                                   ciw.dists.Exponential(.02),
                                   ciw.dists.Exponential(.021),
                                   ciw.dists.Exponential(.02),
                                   ciw.dists.Exponential(.019),
                                   ciw.dists.Exponential(.018),
                                   ciw.dists.Exponential(.015),
                                   ciw.dists.Exponential(.014),
                                   ciw.dists.Exponential(.012),
                                   ciw.dists.Exponential(.01),
                                   ciw.dists.Exponential(.09)],
                         'Class 1':[ciw.dists.Exponential(.06),
                                    ciw.dists.Exponential(.05),
                                    ciw.dists.Exponential(.045),
                                    ciw.dists.Exponential(.04),
                                    ciw.dists.Exponential(.035),
                                    ciw.dists.Exponential(.03),
                                    ciw.dists.Exponential(.025),
                                    ciw.dists.Exponential(.024),
                                    ciw.dists.Exponential(.023),
                                    ciw.dists.Exponential(.022),
                                    ciw.dists.Exponential(.02),
                                    ciw.dists.Exponential(.018),
                                    ciw.dists.Exponential(.015)]},
 routing= {'Class 0':[[0,1,0,0,0,0,0,0,0,0,0,0,0],
                      [0,0,0.1,0.2,0.1,0.02,0.04,0.08,0.05,0.03,0.08,0.1,0],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,0]],
           'Class 1':[[0,1,0,0,0,0,0,0,0,0,0,0,0],
                      [0,0,0.1,0.3,0.1,0.02,0.04,0.08,0.05,0.03,0.08,0.1,0],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,1],
                      [0,0,0,0,0,0,0,0,0,0,0,0,0]],
          },
 number_of_servers=[3,2,1,1,1,1,1,1,1,1,1,1,2]
)
ciw.seed(2)
Q=ciw.simulation(N)
Q.simulate_until_max_time(1440)`

**Comment by geraintpalmer** [comment]
Hi @neetu5510 

Your problem is the line `Q=ciw.simulation(N)`. ciw.simualtion is a module. You want the object, so you need `Q=ciw.Simulation(N)`.

With this change it should run.

**Comment by neetu5510** [comment]
Hey..Thanks a lot...it worked..
