### ISSUE TITLE
docu typo?

### ISSUE THREAD

**Issue by wibrt** [CiwPython/Ciw#179]
On
https://ciw.readthedocs.io/en/latest/Tutorial-II/tutorial_vi.html

It says:
On average the system gets 7.25 broken stools per hour; costing and average of 67.5p per hour of operation.

Whereas the cost per broken stool is 10p

**Comment by wibrt** [comment]
Continuing:

Thus the new system saves an average of 5.875 stools per hour, around 58.75p per hour. Therefore it would take 2500/0.5875≈4255.32 hours of operation for the system to begin paying off.

**Comment by geraintpalmer** [comment]
Thank you very much @wibrt you are correct. I'll fix the documentation now.
