### ISSUE TITLE
How to simulate a customer is impatient in a queue?

### ISSUE THREAD

**Issue by gutangyu** [CiwPython/Ciw#197]
As title,
I want to simulate a situation. When a customer arrive in a store and wait in a queue. After few times passed (maybe 30 seconds, 1 minute, or a threshold), he got  Impatient and wanted to leave the queue (and the system).
I can't find a function is suitable for this situation. Hope someone can help me.
Thanks a lot!

**Comment by geraintpalmer** [comment]
Dear @gutangyu 

This situation is called reneging. We currently have a PR open which implements exactly this. I am hoping to merge as soon possible and I will let you know when it is in.

In the meantime you are still able to access this feature by cloning and pulling down the source files and the relevant branch (`renegeing`)

I hope this helps!

**Comment by gutangyu** [comment]
Dear @geraintpalmer,
Thanks a lot! I can't wait to use it.

By the way, this package is very useful for me. I really thanks your and your team!

**Comment by geraintpalmer** [comment]
Hi @gutangyu this is now implemented in the latest version v.2.3.0:

https://ciw.readthedocs.io/en/latest/Guides/reneging.html

I hope this helps!
