### ISSUE TITLE
[FYI] Are there other types of blocking in queueing networks beyond Type I?

### ISSUE THREAD

**Issue by galenseilis** [CiwPython/Ciw#232]
FYI I asked [Are there other types of blocking in queueing networks beyond Type I?](https://stats.stackexchange.com/questions/632254/are-there-other-types-of-blocking-in-queueing-networks-beyond-type-i). No actions needed. Close issue after reading.

**Comment by geraintpalmer** [comment]
Yes, my go-to reference is: https://www.sciencedirect.com/science/article/abs/pii/0167637786900672

**Type 1**: customers are blocked _after_ finishing service.
**Type 2**: customers are blocked _before_ starting service (that is, service only starts once we know they can move on). I think this is difficult to generalise in networks, where the way ahead might get filled up during the service time.
**Type 3**: customers repeat their service until the path ahead is clear.

Type 3 blocking might be possible in Ciw. I have never seen a need for it though, but could be explored.
