### ISSUE TITLE
[Media Request] Wikipedia Article

### ISSUE THREAD

**Issue by galenseilis** [CiwPython/Ciw#235]
I am starting to draft a Wikipedia page for Ciw. I feel like that will improve the package's adoption. 

May I have permission to use images from the Ciw documentation on this Wikipedia page? Including the Ciw logo?

**Comment by geraintpalmer** [comment]
Of course, no problem :)

**Comment by geraintpalmer** [comment]
Btw, getting through the other issues and pull requests slowly over christmas/new year. Thanks for all the contributions, ideas, and interest :)

**Comment by galenseilis** [comment]
> Btw, getting through the other issues and pull requests slowly over christmas/new year. Thanks for all the contributions, ideas, and interest :)

Thank you! 

Please ensure that you take all the time you need to properly rest at the end of this year. :) ❄️
