### ISSUE TITLE
Parallelise Travis CI

### ISSUE THREAD

**Issue by geraintpalmer** [CiwPython/Ciw#32]
Something like this.

https://docs.travis-ci.com/user/speeding-up-the-build/

**Comment by drvinceknight** [comment]
If speed is (already) becoming an issue I wonder if you should perhaps think of 'downsizing' your tests (run simulation runs for shorter periods of time).

**Comment by geraintpalmer** [comment]
Yep. I think the problem may be hypothesis generating too many things in a single test instance. May just need to reorganise the tests. This is mainly here as it would be cool and thinking about the future mostly.

**Comment by drvinceknight** [comment]
:+1:

**Comment by geraintpalmer** [comment]
Discussed with @drvinceknight, Test suite fairly quick anyway: Travis parallelised for Python 2.7, 3.4, 3.5, so don't think this is worth doing.
