### ISSUE TITLE
Look into Cython

### ISSUE THREAD

**Issue by geraintpalmer** [CiwPython/Ciw#38]
May improve performance... not sure.
Suggestion by @sluenenglish

**Comment by drvinceknight** [comment]
Cython has compilation issues on windows I believe (not saying this is a
bad idea).

Also: numpy.

**Comment by geraintpalmer** [comment]
Thanks, I'll have a look, not really sure what it is yet.

**Comment by drvinceknight** [comment]
http://buff.ly/1oR0f1f

**Comment by geraintpalmer** [comment]
Had a discussion with @drvinceknight , decided to close this May look at a general speed up in the future, but keep in Python.
