### ISSUE TITLE
Phase-Type distrubtions

### ISSUE THREAD

**Issue by geraintpalmer** [CiwPython/Ciw#73]
Add option to sample from phase-type distributions.

**Comment by geraintpalmer** [comment]
Not sure how far @sluenenglish got with his library for this? Could implement that, or start to develop own version...

**Comment by drvinceknight** [comment]
He did get a working library going: https://github.com/sluenenglish/pyphase

I don't believe it's tested and not sure how much he's planning on developing that but it would be worth working on it a bit more. 

Better to get that done up and added as a dependency than to lock phase type capabilities in to ciw. Perhaps see if:

- he (@sluenenglish) is planning/capable on developing it (if only accept pull requests), he's obviously busy now with his job so he might just not have time, or 
- he could give you admin rights to the repo or
- if neither of the above, just fork it and work on your own fork.

**Comment by geraintpalmer** [comment]
Get in touch with Sam. We'd like this packaged, pip installable. Ask Sam what's best here.

**Comment by geraintpalmer** [comment]
Implemented in v.2.2.1 commit efc4f1bd73d4c987e1251e6a7345b014ed7a8377
