### ISSUE TITLE
Add option to run multiple trials

### ISSUE THREAD

**Issue by geraintpalmer** [CiwPython/Ciw#8]
(moving @sluenenglish 's issue from ASQ)

**Comment by geraintpalmer** [comment]
Deciding not to implement this. Can be done simply using a loop (and user can parallelarise as they wish).
Will add a page to docs to show how this may be done though.

**Comment by drvinceknight** [comment]
Good idea.

**Comment by geraintpalmer** [comment]
Implemented in commit 56638e1f931c55a157ff10afbc174674df433d47

Would you mind having a quick look @drvinceknight  (make sure I'm not getting things wrong and not breaking copyright or something). No rush, ta.

**Comment by geraintpalmer** [comment]
Closing, as implemented in docs a while ago.
