### ISSUE TITLE
Gui interface for building simulations

### ISSUE THREAD

**Issue by drvinceknight** [CiwPython/Ciw#84]
Have a play with http://orange.biolab.si/, it's a Python based gui data mining tool. You click and stuff appears which could potentially be a similar way to build a network.

Open source so worth having a look at https://github.com/biolab/orange3

Another idea would be to build something that lives in a browser but could be worth taking a look at orange.

Could be a nice undergrad/summer project.

**Comment by geraintpalmer** [comment]
> Could be a nice undergrad/summer project.

Does this mean I get more ~~minions~~ valuable education based contributors? 😛 

Serious: sounds like a cool idea. Will get looking at orange. I know this is something Paul would like done too! 😃

**Comment by geraintpalmer** [comment]
Closing this, as have decided against adding a GUI
