### ISSUE TITLE
Include a Citation file

### ISSUE THREAD

**Issue by geraintpalmer** [CiwPython/Ciw#88]
Similar to Axelrod: https://github.com/Axelrod-Python/Axelrod/blob/master/CITATION.rst

Look into Zenodo: https://zenodo.org/about

**Comment by geraintpalmer** [comment]
@drvinceknight you've mentioned this before. Any thoughts, opinions?

**Comment by drvinceknight** [comment]
Yeah, this should happen. Could plug in to Zenodo to automatically get a DOI number when a release occurs.

**Comment by geraintpalmer** [comment]
Implemented in commit 25dc4f753eebe7986ba3c4b9638fe339d47bdd15
